version: "3.9"
services:
  giphyx-backend:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8090:8090"
      - "8761:8761"
    environment:
      - MONGODB_HOST=172.16.1.11
      - MONGODB_PORT=27017
    networks:
      backend:
        ipv4_address: 172.16.1.10

  mongodb:
    image: mongo
    expose:
      - 27017
    networks:
      backend:
        ipv4_address: 172.16.1.11

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1